SELECT  * FROM products P
WHERE ROWNUM < = 3
ORDER BY P.price DESC;

WITH ORDERED AS (
    SELECT *
    FROM products
    ORDER BY PRICE DESC
)

SELECT * 
FROM ORDERED 
WHERE ROWNUM <= 3;

SELECT P.*,
COUNT(*) OVER (PARTITION BY PRICE)
FROM PRODUCTS P
ORDER BY P.PRICE;

SELECT P.product_name, P.price,
ROW_NUMBER() OVER (ORDER BY P.PRICE DESC) AS ROW_NUMBER,
RANK() OVER (ORDER BY P.PRICE DESC) AS RANK,
DENSE_RANK() OVER (ORDER BY P.PRICE DESC) AS DENSE_RANK
FROM products P
ORDER BY P.PRICE DESC;


SELECT  * FROM products P
WHERE ROWNUM < = 3
ORDER BY P.price DESC;

WITH NUMBERED AS (
    SELECT product_name, 
    price,
    ROW_NUMBER() OVER (ORDER BY price DESC) AS RN
    FROM products
    ORDER BY PRICE DESC
)

SELECT * 
FROM NUMBERED 
WHERE RN <= 3;

SELECT *
FROM employee
ORDER BY salary DESC
FETCH FIRST 5 ROWS ONLY;
