--- ORDER BY is reserved word in sql to order the thing like DESC or ASC
SELECT *
FROM EMPLOYEE E
ORDER BY E.SALARY DESC;

SELECT *
FROM EMPLOYEE E
ORDER BY E.DEPARTMENT_ID,E.SALARY;

SELECT *
FROM EMPLOYEE
ORDER BY 6,5 DESC;

SELECT *
FROM EMPLOYEE ORDER BY 1;

SELECT E.NAME, E.SALARY + 100 AS NEW_SALARY
FROM EMPLOYEE E
ORDER BY NEW_SALARY;

--- ORDER BY with to use a CASE(switch) expressions
SELECT E.ID, E.NAME, E.DEPARTMENT_ID, E.SALARY
FROM EMPLOYEE E
ORDER BY
    CASE E.DEPARTMENT_ID
    WHEN 1
        THEN E.SALARY
    ELSE E.ID
    END;